import type { ModelConfig, IntentType } from "@/types/routing";

export const MODEL_REGISTRY: ModelConfig[] = [
  // --- Platform defaults (free, powered by Groq) ---
  {
    provider: "groq",
    model: "llama-3.3-70b-versatile",
    label: "Llama 3.3 70B",
    contextWindow: 128000,
    costPer1kInput: 0,
    costPer1kOutput: 0,
    capabilityScore: 0.84,
    strengths: {
      simple_qa: 0.86,
      code_generation: 0.82,
      creative_writing: 0.80,
      data_analysis: 0.78,
      multi_step_task: 0.76,
      code_review: 0.74,
      web_research: 0.70,
    },
    avgLatencyMs: 900,
    supportsTools: true,
    supportsVision: false,
    supportsStreaming: true,
    isPlatformDefault: true,
  },
  {
    provider: "groq",
    model: "llama-3.1-8b-instant",
    label: "Llama 3.1 8B",
    contextWindow: 128000,
    costPer1kInput: 0,
    costPer1kOutput: 0,
    capabilityScore: 0.56,
    strengths: {
      simple_qa: 0.72,
      web_research: 0.64,
      creative_writing: 0.62,
    },
    avgLatencyMs: 350,
    supportsTools: true,
    supportsVision: false,
    supportsStreaming: true,
    isPlatformDefault: true,
  },
  {
    provider: "groq",
    model: "mixtral-8x7b-32768",
    label: "Mixtral 8x7B",
    contextWindow: 32768,
    costPer1kInput: 0,
    costPer1kOutput: 0,
    capabilityScore: 0.72,
    strengths: {
      code_generation: 0.78,
      code_review: 0.74,
      data_analysis: 0.74,
      math_reasoning: 0.72,
      simple_qa: 0.68,
    },
    avgLatencyMs: 700,
    supportsTools: false,
    supportsVision: false,
    supportsStreaming: true,
    isPlatformDefault: true,
  },
  // --- User-provided premium models ---
  {
    provider: "anthropic",
    model: "claude-3-5-sonnet-20241022",
    label: "Claude 3.5 Sonnet",
    contextWindow: 200000,
    costPer1kInput: 0.003,
    costPer1kOutput: 0.015,
    capabilityScore: 0.95,
    strengths: {
      code_generation: 1.0,
      code_review: 1.0,
      multi_step_task: 0.95,
      long_document_analysis: 0.95,
      creative_writing: 0.88,
      data_analysis: 0.85,
      simple_qa: 0.82,
      math_reasoning: 0.78,
    },
    avgLatencyMs: 2500,
    supportsTools: true,
    supportsVision: true,
    supportsStreaming: true,
  },
  {
    provider: "anthropic",
    model: "claude-3-haiku-20240307",
    label: "Claude 3 Haiku",
    contextWindow: 200000,
    costPer1kInput: 0.00025,
    costPer1kOutput: 0.00125,
    capabilityScore: 0.62,
    strengths: {
      simple_qa: 0.82,
      creative_writing: 0.62,
      code_generation: 0.58,
      data_analysis: 0.60,
    },
    avgLatencyMs: 700,
    supportsTools: true,
    supportsVision: false,
    supportsStreaming: true,
  },
  {
    provider: "openai",
    model: "gpt-4o",
    label: "GPT-4o",
    contextWindow: 128000,
    costPer1kInput: 0.0025,
    costPer1kOutput: 0.01,
    capabilityScore: 0.92,
    strengths: {
      image_understanding: 1.0,
      creative_writing: 0.92,
      data_analysis: 0.88,
      simple_qa: 0.88,
      web_research: 0.85,
      code_generation: 0.82,
      code_review: 0.80,
      multi_step_task: 0.80,
      math_reasoning: 0.78,
    },
    avgLatencyMs: 1800,
    supportsTools: true,
    supportsVision: true,
    supportsStreaming: true,
  },
  {
    provider: "openai",
    model: "gpt-4o-mini",
    label: "GPT-4o Mini",
    contextWindow: 128000,
    costPer1kInput: 0.00015,
    costPer1kOutput: 0.0006,
    capabilityScore: 0.70,
    strengths: {
      simple_qa: 0.78,
      creative_writing: 0.74,
      data_analysis: 0.68,
      code_generation: 0.66,
    },
    avgLatencyMs: 800,
    supportsTools: true,
    supportsVision: false,
    supportsStreaming: true,
  },
  {
    provider: "openai",
    model: "o3-mini",
    label: "o3 Mini",
    contextWindow: 128000,
    costPer1kInput: 0.0011,
    costPer1kOutput: 0.0044,
    capabilityScore: 0.93,
    strengths: {
      math_reasoning: 1.0,
      code_generation: 0.95,
      data_analysis: 0.90,
      code_review: 0.88,
      multi_step_task: 0.82,
    },
    avgLatencyMs: 3500,
    supportsTools: false,
    supportsVision: false,
    supportsStreaming: true,
  },
  {
    provider: "google",
    model: "gemini-2.0-flash",
    label: "Gemini 2.0 Flash",
    contextWindow: 1000000,
    costPer1kInput: 0.0001,
    costPer1kOutput: 0.0004,
    capabilityScore: 0.82,
    strengths: {
      long_document_analysis: 1.0,
      image_understanding: 0.88,
      web_research: 0.88,
      simple_qa: 0.84,
      data_analysis: 0.80,
      code_generation: 0.76,
    },
    avgLatencyMs: 1200,
    supportsTools: true,
    supportsVision: true,
    supportsStreaming: true,
  },
  {
    provider: "google",
    model: "gemini-2.0-flash-thinking-exp",
    label: "Gemini 2.0 Thinking",
    contextWindow: 1000000,
    costPer1kInput: 0.0,
    costPer1kOutput: 0.0,
    capabilityScore: 0.88,
    strengths: {
      math_reasoning: 0.93,
      code_generation: 0.88,
      data_analysis: 0.84,
      multi_step_task: 0.80,
    },
    avgLatencyMs: 4000,
    supportsTools: false,
    supportsVision: false,
    supportsStreaming: true,
  },
];

export const TASK_TYPE_LABELS: Record<IntentType, string> = {
  simple_qa: "Quick answer",
  long_document_analysis: "Document analysis",
  code_generation: "Code generation",
  code_review: "Code review",
  creative_writing: "Creative writing",
  data_analysis: "Data analysis",
  web_research: "Web research",
  math_reasoning: "Math / reasoning",
  image_understanding: "Image analysis",
  multi_step_task: "Multi-step task",
};
