import type { ModelConfig, IntentType } from "@/types/routing";

export const MODEL_REGISTRY: ModelConfig[] = [
  {
    provider: "anthropic",
    model: "claude-3-5-sonnet-20241022",
    label: "Claude 3.5 Sonnet",
    contextWindow: 200000,
    costPer1kInput: 0.003,
    costPer1kOutput: 0.015,
    strengths: ["long_document_analysis", "code_generation", "code_review", "multi_step_task"],
    avgLatencyMs: 2500,
    supportsTools: true,
    supportsVision: true,
    supportsStreaming: true,
  },
  {
    provider: "anthropic",
    model: "claude-3-haiku-20240307",
    label: "Claude 3 Haiku",
    contextWindow: 200000,
    costPer1kInput: 0.00025,
    costPer1kOutput: 0.00125,
    strengths: ["simple_qa"],
    avgLatencyMs: 700,
    supportsTools: true,
    supportsVision: false,
    supportsStreaming: true,
  },
  {
    provider: "openai",
    model: "gpt-4o",
    label: "GPT-4o",
    contextWindow: 128000,
    costPer1kInput: 0.0025,
    costPer1kOutput: 0.01,
    strengths: ["simple_qa", "creative_writing", "data_analysis", "image_understanding"],
    avgLatencyMs: 1800,
    supportsTools: true,
    supportsVision: true,
    supportsStreaming: true,
  },
  {
    provider: "openai",
    model: "gpt-4o-mini",
    label: "GPT-4o Mini",
    contextWindow: 128000,
    costPer1kInput: 0.00015,
    costPer1kOutput: 0.0006,
    strengths: ["simple_qa"],
    avgLatencyMs: 800,
    supportsTools: true,
    supportsVision: false,
    supportsStreaming: true,
  },
  {
    provider: "openai",
    model: "o3-mini",
    label: "o3 Mini",
    contextWindow: 128000,
    costPer1kInput: 0.0011,
    costPer1kOutput: 0.0044,
    strengths: ["math_reasoning", "code_generation", "data_analysis"],
    avgLatencyMs: 3500,
    supportsTools: false,
    supportsVision: false,
    supportsStreaming: true,
  },
  {
    provider: "google",
    model: "gemini-2.0-flash",
    label: "Gemini 2.0 Flash",
    contextWindow: 1000000,
    costPer1kInput: 0.0001,
    costPer1kOutput: 0.0004,
    strengths: ["long_document_analysis", "simple_qa", "web_research"],
    avgLatencyMs: 1200,
    supportsTools: true,
    supportsVision: true,
    supportsStreaming: true,
  },
  {
    provider: "google",
    model: "gemini-2.0-flash-thinking-exp",
    label: "Gemini 2.0 Thinking",
    contextWindow: 1000000,
    costPer1kInput: 0.0,
    costPer1kOutput: 0.0,
    strengths: ["math_reasoning", "code_generation"],
    avgLatencyMs: 4000,
    supportsTools: false,
    supportsVision: false,
    supportsStreaming: true,
  },
];

export const TASK_TYPE_LABELS: Record<IntentType, string> = {
  simple_qa: "Quick answer",
  long_document_analysis: "Document analysis",
  code_generation: "Code generation",
  code_review: "Code review",
  creative_writing: "Creative writing",
  data_analysis: "Data analysis",
  web_research: "Web research",
  math_reasoning: "Math / reasoning",
  image_understanding: "Image analysis",
  multi_step_task: "Multi-step task",
};
